### ISSUE TITLE
head look at hand does not work

### ISSUE THREAD

**Issue by robinsoetens** [tue-robotics/robot_skills#13]
Using amigo console with: amigo.head.look_at_hand("left",True) does not work. Does not give an error either

**Comment by Rayman** [comment]
It now gives an error because `amigo.head.look_at_hand` only has one parameter: `side`. @reinzor is the `keep_tracking` parameter a mistake in the documentation does it have to be implemented?

**Comment by reinzor** [comment]
The keep tracking parameter is out of the api. It tracks by default
otherwise you should specify a point in base link frame or something but
this is mostly undesired. You can call a cancel_goal() to cancel the
specified goal.

So either close the issue or provide decent motivation why the current api
is wrong.

-Rein

**Comment by jlunenburg** [comment]
I guess time will tell: it was there for a reason. Another issue, however, is that the set pan tilt function has been completely removed. Although this shouldn't be used in executives, it's extremely useful in the [robot]-console for testing camera stuff...

**Comment by reinzor** [comment]
Then please implement head.look_down() functions etc; no pan tilt; this
cannot be made generic.

-Rein

**Comment by LoyVanBeek** [comment]
We can define a couple of standard points to look at relative to base_link? Look_down then just looks at one of those points.

**Comment by reinzor** [comment]
yup

-Rein

**Comment by jlunenburg** [comment]
We could, but for testing purposes that's not what you want...
